apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: nginx-app
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
    - port: 80 # The port that the service will expose
      targetPort: 80 # The port on the container (nginx container's port)
      nodePort: 30007 # The port exposed on the node (must be in the range 30000-32767)
